// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat/proto/chat.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat/proto/chat.proto

It has these top-level messages:
	SendPMReq
	SendPMRes
	PushMsg
	SentPrivateMsg
	UserOnlineReq
	UserOnlineRes
	UserOfflineReq
	UserOfflineRes
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SendPMReq struct {
	FromUID string `protobuf:"bytes,1,opt,name=fromUID" json:"fromUID,omitempty"`
	ToUID   string `protobuf:"bytes,2,opt,name=toUID" json:"toUID,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *SendPMReq) Reset()                    { *m = SendPMReq{} }
func (m *SendPMReq) String() string            { return proto1.CompactTextString(m) }
func (*SendPMReq) ProtoMessage()               {}
func (*SendPMReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendPMReq) GetFromUID() string {
	if m != nil {
		return m.FromUID
	}
	return ""
}

func (m *SendPMReq) GetToUID() string {
	if m != nil {
		return m.ToUID
	}
	return ""
}

func (m *SendPMReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendPMRes struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *SendPMRes) Reset()                    { *m = SendPMRes{} }
func (m *SendPMRes) String() string            { return proto1.CompactTextString(m) }
func (*SendPMRes) ProtoMessage()               {}
func (*SendPMRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendPMRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendPMRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type PushMsg struct {
	Command string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Body    []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *PushMsg) Reset()                    { *m = PushMsg{} }
func (m *PushMsg) String() string            { return proto1.CompactTextString(m) }
func (*PushMsg) ProtoMessage()               {}
func (*PushMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PushMsg) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *PushMsg) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type SentPrivateMsg struct {
	Req           *SendPMReq `protobuf:"bytes,1,opt,name=req" json:"req,omitempty"`
	SentTimestamp int64      `protobuf:"varint,2,opt,name=sentTimestamp" json:"sentTimestamp,omitempty"`
}

func (m *SentPrivateMsg) Reset()                    { *m = SentPrivateMsg{} }
func (m *SentPrivateMsg) String() string            { return proto1.CompactTextString(m) }
func (*SentPrivateMsg) ProtoMessage()               {}
func (*SentPrivateMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SentPrivateMsg) GetReq() *SendPMReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *SentPrivateMsg) GetSentTimestamp() int64 {
	if m != nil {
		return m.SentTimestamp
	}
	return 0
}

type UserOnlineReq struct {
	Uid     string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	WebNode string `protobuf:"bytes,2,opt,name=webNode" json:"webNode,omitempty"`
}

func (m *UserOnlineReq) Reset()                    { *m = UserOnlineReq{} }
func (m *UserOnlineReq) String() string            { return proto1.CompactTextString(m) }
func (*UserOnlineReq) ProtoMessage()               {}
func (*UserOnlineReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserOnlineReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserOnlineReq) GetWebNode() string {
	if m != nil {
		return m.WebNode
	}
	return ""
}

type UserOnlineRes struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *UserOnlineRes) Reset()                    { *m = UserOnlineRes{} }
func (m *UserOnlineRes) String() string            { return proto1.CompactTextString(m) }
func (*UserOnlineRes) ProtoMessage()               {}
func (*UserOnlineRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserOnlineRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserOnlineRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type UserOfflineReq struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *UserOfflineReq) Reset()                    { *m = UserOfflineReq{} }
func (m *UserOfflineReq) String() string            { return proto1.CompactTextString(m) }
func (*UserOfflineReq) ProtoMessage()               {}
func (*UserOfflineReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserOfflineReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserOfflineRes struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *UserOfflineRes) Reset()                    { *m = UserOfflineRes{} }
func (m *UserOfflineRes) String() string            { return proto1.CompactTextString(m) }
func (*UserOfflineRes) ProtoMessage()               {}
func (*UserOfflineRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserOfflineRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserOfflineRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto1.RegisterType((*SendPMReq)(nil), "proto.SendPMReq")
	proto1.RegisterType((*SendPMRes)(nil), "proto.SendPMRes")
	proto1.RegisterType((*PushMsg)(nil), "proto.PushMsg")
	proto1.RegisterType((*SentPrivateMsg)(nil), "proto.SentPrivateMsg")
	proto1.RegisterType((*UserOnlineReq)(nil), "proto.UserOnlineReq")
	proto1.RegisterType((*UserOnlineRes)(nil), "proto.UserOnlineRes")
	proto1.RegisterType((*UserOfflineReq)(nil), "proto.UserOfflineReq")
	proto1.RegisterType((*UserOfflineRes)(nil), "proto.UserOfflineRes")
}

func init() { proto1.RegisterFile("chat/proto/chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x0d, 0x16, 0xa8, 0x8c, 0x42, 0xc8, 0x06, 0x0c, 0xe1, 0x64, 0x36, 0x1e, 0x8c, 0x07, 0x48,
	0x50, 0xc3, 0xc1, 0x78, 0xd0, 0x78, 0xf1, 0x80, 0x92, 0x22, 0x17, 0x6f, 0xa5, 0x1d, 0xa0, 0x89,
	0xdd, 0x85, 0x9d, 0x05, 0xe3, 0xdf, 0x9b, 0xdd, 0x6e, 0x51, 0x10, 0x2f, 0x9c, 0x3a, 0xef, 0xf5,
	0xcd, 0xec, 0x7b, 0x0f, 0x9a, 0xd1, 0x3c, 0xd4, 0xdd, 0x85, 0x92, 0x5a, 0x76, 0xcd, 0xd8, 0xb1,
	0x23, 0x2b, 0xd9, 0x0f, 0x1f, 0x43, 0x65, 0x84, 0x22, 0x1e, 0x0e, 0x02, 0x5c, 0xb2, 0x16, 0xf8,
	0x53, 0x25, 0xd3, 0xf1, 0xf3, 0x53, 0xab, 0x70, 0x5e, 0xb8, 0xac, 0x04, 0x39, 0x64, 0x0d, 0x28,
	0x69, 0x69, 0xf8, 0x23, 0xcb, 0x67, 0xc0, 0xe8, 0x23, 0x29, 0x34, 0x0a, 0xdd, 0xf2, 0x32, 0xbd,
	0x83, 0xfc, 0xfe, 0xe7, 0x2c, 0x19, 0x19, 0xad, 0xa2, 0x08, 0x89, 0xec, 0xd9, 0xe3, 0x20, 0x87,
	0xec, 0x0c, 0xca, 0xa8, 0xd4, 0x80, 0x66, 0xee, 0xae, 0x43, 0xbc, 0x0f, 0xfe, 0x70, 0x45, 0xf3,
	0x01, 0xcd, 0xb2, 0x37, 0xd2, 0x34, 0x14, 0x71, 0xee, 0xc9, 0x41, 0xc6, 0xa0, 0x38, 0x91, 0xf1,
	0x97, 0x5d, 0x3d, 0x0d, 0xec, 0xcc, 0xdf, 0xa1, 0x36, 0x42, 0xa1, 0x87, 0x2a, 0x59, 0x87, 0x1a,
	0xcd, 0x3e, 0x07, 0x4f, 0xe1, 0xd2, 0xee, 0x9e, 0xf4, 0xea, 0x59, 0xf8, 0xce, 0x26, 0x72, 0x60,
	0x7e, 0xb2, 0x0b, 0xa8, 0x12, 0x0a, 0xfd, 0x96, 0xa4, 0x48, 0x3a, 0x4c, 0x17, 0xf6, 0xa4, 0x17,
	0x6c, 0x93, 0xfc, 0x0e, 0xaa, 0x63, 0x42, 0xf5, 0x2a, 0x3e, 0x12, 0x81, 0xa6, 0xae, 0x3a, 0x78,
	0xab, 0x24, 0xb7, 0x65, 0x46, 0x63, 0xf6, 0x13, 0x27, 0x2f, 0x32, 0x46, 0x17, 0x28, 0x87, 0xfc,
	0x61, 0x7b, 0xf9, 0x90, 0x52, 0x38, 0xd4, 0xec, 0x89, 0xe9, 0xf4, 0x5f, 0x03, 0xfc, 0x71, 0x47,
	0x73, 0xc0, 0x3b, 0xbd, 0x5b, 0xf0, 0x5d, 0x7f, 0xec, 0x0a, 0x8a, 0xa6, 0x2a, 0xf6, 0xa7, 0xb7,
	0xf6, 0x2e, 0x43, 0xbd, 0x35, 0x94, 0x46, 0xda, 0x2c, 0xdd, 0x40, 0x39, 0x8b, 0xc9, 0x1a, 0x4e,
	0xb4, 0x55, 0x5b, 0x7b, 0x1f, 0x4b, 0xac, 0x0f, 0xbe, 0x73, 0xcd, 0x9a, 0xbf, 0x05, 0x9b, 0xb4,
	0xed, 0xbd, 0x34, 0x4d, 0xca, 0x96, 0xbd, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x82, 0x25,
	0x2d, 0xe8, 0x02, 0x00, 0x00,
}
