// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth/proto/auth.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	auth/proto/auth.proto

It has these top-level messages:
	LoginReq
	LoginRes
	CheckAuthReq
	CheckAuthRes
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRes, error)
	Check(ctx context.Context, in *CheckAuthReq, opts ...client.CallOption) (*CheckAuthRes, error)
}

type authService struct {
	c           client.Client
	serviceName string
}

func AuthServiceClient(serviceName string, c client.Client) AuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto"
	}
	return &authService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authService) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRes, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Login", in)
	out := new(LoginRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Check(ctx context.Context, in *CheckAuthReq, opts ...client.CallOption) (*CheckAuthRes, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Check", in)
	out := new(CheckAuthRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	Login(context.Context, *LoginReq, *LoginRes) error
	Check(context.Context, *CheckAuthReq, *CheckAuthRes) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Auth{hdlr}, opts...))
}

type Auth struct {
	AuthHandler
}

func (h *Auth) Login(ctx context.Context, in *LoginReq, out *LoginRes) error {
	return h.AuthHandler.Login(ctx, in, out)
}

func (h *Auth) Check(ctx context.Context, in *CheckAuthReq, out *CheckAuthRes) error {
	return h.AuthHandler.Check(ctx, in, out)
}
