// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/proto/auth.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	auth/proto/auth.proto

It has these top-level messages:
	LoginReq
	LoginRes
	CheckAuthReq
	CheckAuthRes
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto1.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRes struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	Uid     string `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
	Token   string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *LoginRes) Reset()                    { *m = LoginRes{} }
func (m *LoginRes) String() string            { return proto1.CompactTextString(m) }
func (*LoginRes) ProtoMessage()               {}
func (*LoginRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *LoginRes) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckAuthReq struct {
	Uid   string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *CheckAuthReq) Reset()                    { *m = CheckAuthReq{} }
func (m *CheckAuthReq) String() string            { return proto1.CompactTextString(m) }
func (*CheckAuthReq) ProtoMessage()               {}
func (*CheckAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CheckAuthReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CheckAuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckAuthRes struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *CheckAuthRes) Reset()                    { *m = CheckAuthRes{} }
func (m *CheckAuthRes) String() string            { return proto1.CompactTextString(m) }
func (*CheckAuthRes) ProtoMessage()               {}
func (*CheckAuthRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CheckAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CheckAuthRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto1.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto1.RegisterType((*LoginRes)(nil), "proto.LoginRes")
	proto1.RegisterType((*CheckAuthReq)(nil), "proto.CheckAuthReq")
	proto1.RegisterType((*CheckAuthRes)(nil), "proto.CheckAuthRes")
}

func init() { proto1.RegisterFile("auth/proto/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x4f, 0x4f, 0x84, 0x30,
	0x10, 0xc5, 0xc3, 0xee, 0x76, 0xc5, 0x89, 0x89, 0x66, 0xfc, 0x93, 0x86, 0x93, 0xe1, 0xa4, 0x97,
	0xdd, 0xa8, 0x89, 0x67, 0xff, 0x5c, 0xf5, 0xc2, 0x37, 0x40, 0xda, 0x2c, 0x84, 0x48, 0xb1, 0xd3,
	0xc6, 0xaf, 0x6f, 0x3a, 0x14, 0x82, 0x86, 0x93, 0x27, 0xe6, 0xbd, 0x97, 0xdf, 0xf0, 0x3a, 0x70,
	0x59, 0x7a, 0x57, 0xef, 0x7b, 0x6b, 0x9c, 0xd9, 0x87, 0x71, 0xc7, 0x23, 0x0a, 0xfe, 0xe4, 0x2f,
	0x90, 0xbe, 0x99, 0x43, 0xd3, 0x15, 0xfa, 0x0b, 0x33, 0x48, 0x3d, 0x69, 0xdb, 0x95, 0x9f, 0x5a,
	0x26, 0xd7, 0xc9, 0xcd, 0x71, 0x31, 0xe9, 0x90, 0xf5, 0x25, 0xd1, 0xb7, 0xb1, 0x4a, 0xae, 0x86,
	0x6c, 0xd4, 0xb9, 0x9a, 0x76, 0x10, 0x4a, 0x38, 0x22, 0x5f, 0x55, 0x9a, 0x88, 0x57, 0xa4, 0xc5,
	0x28, 0xf1, 0x0a, 0xb6, 0xda, 0xda, 0x77, 0x3a, 0x44, 0x3e, 0x2a, 0x3c, 0x83, 0xb5, 0x6f, 0x94,
	0x5c, 0xb3, 0x19, 0x46, 0xbc, 0x00, 0xe1, 0x4c, 0xab, 0x3b, 0xb9, 0x61, 0x6f, 0x10, 0xf9, 0x23,
	0x9c, 0xbc, 0xd6, 0xba, 0x6a, 0x9f, 0xbd, 0xab, 0x43, 0xdb, 0xc8, 0x25, 0x0b, 0xdc, 0x6a, 0xce,
	0x3d, 0xfd, 0xe2, 0xfe, 0xd1, 0xf0, 0x5e, 0xc1, 0x26, 0xc0, 0x78, 0x0b, 0x82, 0xdf, 0x89, 0xa7,
	0xc3, 0x0d, 0x77, 0xe3, 0xe5, 0xb2, 0x3f, 0x06, 0xe1, 0x1d, 0x08, 0xfe, 0x29, 0x9e, 0xc7, 0x64,
	0x5e, 0x3d, 0x5b, 0x30, 0xe9, 0x63, 0xcb, 0xde, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17,
	0x43, 0x9a, 0x5e, 0xb0, 0x01, 0x00, 0x00,
}
